!spring.datasource1.jdbc-url=jdbc:postgresql://192.168.0.240;databaseName=IGM_SALUD
!spring.datasource1.url=jdbc:postgresql://localhost:5432/IGM_SALUD
!spring.datasource1.username=postgres
!spring.datasource1.password=Passw0rd
!spring.datasource1.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver


!spring.datasource.jdbc-url=jdbc:postgresql://localhost:5433/igm_salud_master?escapeSyntaxCallMode=callIfNoReturn
spring.datasource.jdbc-url=jdbc:postgresql://localhost:5432/igm_salud_master?escapeSyntaxCallMode=callIfNoReturn
spring.datasource.username=postgres
spring.datasource.password=Passw0rd
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.datasource.escapeSyntaxCallMode= true



!spring.datasource1.jdbc-url=jdbc:sqlserver://192.168.0.240;databaseName=IGM_SALUD
!spring.datasource1.username=hce
!spring.datasource1.password=Hnal#2021
!spring.datasource1.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
!spring.jpa.show-sql=true
spring.main.allow-circular-references:true



#second db
!spring.second-db..jdbc-url=jdbc:sqlserver://192.168.0.240;databaseName=MAESTROS
!spring.second-db.username=hce
!spring.second-db.password=Hnal#2021
!spring.second-db.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver



! spring.datasource.hikari.connectionTimeout=60000 > 
!spring.datasource.hikari.idleTimeout=600000 
!spring.datasource.hikari.maxLifetime=1800000 
!server.address=192.168.80.199
server.address=0.0.0.0
server.port=8090



# Configuración para enviar correos electrónicos hotmail
#spring.mail.host=smtp.live.com
spring.mail.host=smtp.office365.com
spring.mail.port=587
spring.mail.username=igmccorporation@hotmail.com
spring.mail.password=Igmc$$;1..20231
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


# Configuración para enviar correos electrónicos gmail
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=igmccorporation@gmail.com
#spring.mail.password=Igmc$$;1..20231
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
