spring.application.name=api_salud
# CONEXION POSTGRESQL HNAL
# 1. URL de conexión (He quitado channel_binding porque a veces da problemas en local)
spring.datasource.url=jdbc:postgresql://ep-autumn-hall-amb6el40-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require&escapeSyntaxCallMode=callIfNoReturn

# 2. El Role (Usuario) es neondb_owner (Asegúrate de no tener espacios extra)
spring.datasource.username=neondb_owner

# 3. La contraseña (Cópiala directamente dándole a "Show password" en tu panel)
spring.datasource.password=npg_LDyN1QUMGu4l



# 5. Optimización para Hibernate (Evita que intente validar metadatos que bloquean el inicio)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

#spring.datasource.url=jdbc:postgresql://localhost:5432/igm_salud_master?escapeSyntaxCallMode=callIfNoReturn
#spring.datasource.url=jdbc:postgresql://localhost:5433/igm_salud_master?escapeSyntaxCallMode=callIfNoReturn
#spring.datasource.username=postgres
#spring.datasource.password=Passw0rd
spring.datasource.driver-class-name=org.postgresql.Driver

# configuracion del puerto 
server.address=0.0.0.0+++
server.port=8090

# Configuración para enviar correos electrónicos hotmail
#spring.mail.host=smtp.live.com
#spring.mail.host=smtp.office365.com
#spring.mail.port=587
#spring.mail.username=igmccorporation@hotmail.com
#spring.mail.password=Igmc$$;1..20261
#spring.mail.password=vwnmbaocrlkbctxd
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true


spring.mail.username=ngeldres@igmccorp.com
spring.mail.password=Zoja362
spring.mail.host=smtp.claroempresas.com.pe
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



